[package]
name = "odds"
version = "0.2.2"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "Odds and ends — collection miscellania. The goal of this crate is to abolish itself. Things that are here will move to other places when possible."
documentation = "http://bluss.github.io/arrayvec/doc/odds"
repository = "https://github.com/bluss/odds"

keywords = ["data-structure", "unchecked", "range", "debug-assert", "fix-combinator"]

[dependencies]

unreachable = { version = "0.0.2" }

[features]
unstable = []
